option('build-components',            type: 'boolean', value: true,  description: 'build unity-platform-components library.')
option('build-quit',                  type: 'boolean', value: true,  description: 'build unity-platform-quit library.')
option('build-wlr',                   type: 'boolean', value: true,  description: 'build unity-platform-wlr library.')
option('build-backgrounds',           type: 'boolean', value: true,  description: 'build unity-platform-backgrounds library.')
option('build-translucency',          type: 'boolean', value: true,  description: 'build unity-platform-translucency library.')
option('documentation',               type: 'boolean', value: false, description: 'Build API reference with gi-docgen.')
